-- AlterTable
ALTER TABLE "Cart" ALTER COLUMN "quantity_0" SET DEFAULT 0,
ALTER COLUMN "quantity_1" SET DEFAULT 0,
ALTER COLUMN "quantity_2" SET DEFAULT 0,
ALTER COLUMN "quantity_3" SET DEFAULT 0,
ALTER COLUMN "quantity_4" SET DEFAULT 0,
ALTER COLUMN "quantity_5" SET DEFAULT 0,
ALTER COLUMN "quantity_6" SET DEFAULT 0,
ALTER COLUMN "quantity_7" SET DEFAULT 0,
ALTER COLUMN "quantity_8" SET DEFAULT 0,
ALTER COLUMN "quantity_9" SET DEFAULT 0,
ALTER COLUMN "quantity_10" SET DEFAULT 0,
ALTER COLUMN "quantity_11" SET DEFAULT 0,
ALTER COLUMN "total" SET DEFAULT 0;
