import NavBar from "@/components/NavBar";
import "./globals.css";
import { Inter, Cormorant } from "next/font/google";
import Socials from "@/components/Socials";
import Cart from "@/components/Cart";
import Link from "next/link";
import DropdownMenu from "@/components/DropdownMenu";

import AuthProviders from "./context/AuthProvider";
import SignIOBtn from "@/components/SignIOBtn";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});
const cormorant = Cormorant({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-cormorant",
});

export const metadata = {
  title: "Lucky Plants",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  

  return (
    <html
      lang="en"
      id="root"
      className={`${cormorant.variable} ${inter.variable}`}
    >
      <body className="flex flex-col justify-center h-full min-h-screen p-4 font-sans bg-gradient-to-r from-lime-100 to-green-100 relative">
        {/* <QueryClientProvider client={queryClient}> */}
        <AuthProviders>
          {/* TOP MENU */}
          <div className="relative w-4/5 mx-auto max-w-7xl">
            <div className="flex justify-between items-center invisible lg:visible absolute w-full">
              <Link href="/" className="">
                <h1 className="font-serif text-4xl lg:text-5xl xl:text-6xl font-semibold text-green-900">
                  Lucky
                </h1>
              </Link>
              {/* NAVIGATION */}
              <div className="">
                <NavBar isMobile={false}/>
              </div>
              {/* CART */}
              <div className='flex items-center'>
                <Link href="/cart" className="mr-8">
                  <Cart />
                </Link>
                <SignIOBtn />
              </div>
            </div>
            <div className="flex justify-between items-center lg:invisible absolute w-full">
              <DropdownMenu />
              <Link href="/" className="">
                <h1 className="font-serif text-4xl font-semibold text-green-900">
                  Lucky
                </h1>
              </Link>
              <Link href="/cart" className="">
                <Cart />
              </Link>
            </div>
          </div>
          <div className="mt-20 w-full">{children}</div>
          <footer className="mt-auto mx-auto left-0 right-0 pt-4">
            <Socials />
          </footer>
        </AuthProviders>
        {/* </QueryClientProvider> */}
      </body>
    </html>
  );
}
